### PR TITLE
Add support for formatted output

### PR DESCRIPTION
**Pull request by 0X1A**
Allows for formatting via `-f`, similar to @cholcombe973's #5 where some examples are:
`ceph -e -f json`

```
{"Removable":[1,0,2],"Not Removable":[],"Pending":[]}
```

and `ceph -q -f json`

```
{"Safe to remove an OSD":true}
```

### CODE REVIEW

**Comment by cholcombe973** [comment]
Wow this is great! Thanks I'll try it out as soon as I can.

**Comment by cholcombe973** [comment]
Looks good.  I'll get this built on the PPA.  Next question is where should we put the PPA files so everyone has access?

**Comment by 0X1A** [comment]
@cholcombe973 Would it be a bad idea or form to include it in this repo?

**Comment by cholcombe973** [comment]
Yeah I can do that when I get back from the charmer summit.

**Comment by 0X1A** [comment]
@cholcombe973 awesome  :sunglasses:

**Comment by cholcombe973** [comment]
done

**Pull request merged**
